### ISSUE TITLE
[ Pre-Task ] PrincipalDetails 클래스 구현

### ISSUE THREAD

**Issue by jun02160** [Late-Night-Restaurant/backend-pre-task#5]
## 종류

ISSUE 종류를 선택하세요 

Refactor
Fix
Bug
Feature

## 내용

-

## 체크리스트

- [ ] 칸반보드에 있는 에픽 번호를 이슈 이름에 명시
  - EX `[ {페이지명} - {세부명} ] 테스트 이슈명`
- [ ] Assignees / Labels / Milestone 선택
- [ ] ...todos, ...alert

**Comment by weejinyoung** [comment]
종료
