### ISSUE TITLE
[ Study ] 카카오 로그인 과정 이해

### ISSUE THREAD

**Issue by weejinyoung** [Late-Night-Restaurant/backend-pre-task#9]
## 종류

Study

## 내용

- OauthService 리팩토링을 위한 카카오로그인 과정 이해

## 체크리스트

- [x] 왁
- [x] 마이콜
- [x] 채니
- [x] 쭈니

**Comment by jun02160** [comment]
[소셜 로그인 API 로직]
![KakaoTalk_Photo_2023-01-09-04-04-48](https://user-images.githubusercontent.com/80024278/211214141-f1a96cac-1e30-4141-94d7-57c318f050d0.jpeg)

[OauthService method]
- getKakaoAccessToken() 
   인가코드를 이용해 백에서 카카오 서버로 Access Token을 요청 -> Access Token 발급하여 백으로 리턴 [KakaoTokenDto]
- getKakaoInfo()
   Access Token을 이용해 카카오 서버에 저장된 회원정보 요청 -> 백으로 정보 리턴하면 백은 DB에 정보를 저장
- kakaoLogin()
   loginDto를 생성하여 받아온 회원정보로 로그인 시도
- kakaoSignup()
   새로운 User 객체 생성 후, 리포지토리에 저장 -> 소셜로그인으로 회원가입 시 Refresh Token 생성 후 리포지토리에 저장

**Comment by jun02160** [comment]
https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#kakaologin

**Comment by ChaeyeonHan** [comment]
## 소셜로그인 흐름
![image](https://user-images.githubusercontent.com/71596178/211245193-65356c8a-5920-4beb-a979-ccd919221b91.png)

1. 클라이언트가 로그인을 한다
2. 카카오 서버는 redirect url로 (인가)code를 전달해준다.
3, 4 (인가)code를 이용하여 access_token을 발급받는다.
5.  access_token을 서버로 전송한다.
6, 7 서버에서 받은 access_token을 이용하여 카카오 서버에서 사용자 정보를 받는다.
8. 받은 사용자 정보를 이용하여 회원가입, 로그인을 진행한다
9. JWT와 같은 사용자 식별 정보를 클라이언트로 보낸다.

## 카카오 로그인 이해하기
### (1) 인가코드 받아오기
![image](https://user-images.githubusercontent.com/71596178/211245033-a59a7b21-20e3-4bf3-bf08-c6183aff4815.png)

- 서버가 카카오 인증 서버로 인가코드를 요청한다.
    - GET /oauth/authorize
    - ``` java  // 인가코드 받기
          GET /oauth/authorize?client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code HTTP/1.1
          Host: kauth.kakao.com
      ```
    - 카카오 로그인 동의 화면을 호출하고, 사용자 동의를 통해 인가코드를 redirect uri로 발급해준다. 
    - 서버는 요청 처리 결과를 담은 쿼리스트링을 redirect_uri로 HTTP 302 리다이렉트 해준다.

- 카카오 인증 서버가 사용자에게, 카카오계정 로그인을 통한 인증을 요청한다.
    - 클라이언트에 유효한 카카오계정 세션이 있거나, 카카오톡 인앱 브라우저에서의 요청인 경우, 생략된다.
    - 사용자가 카카오계정으로 로그인한 상태라면 이미 카카오계정 세션이 존재한다.
- 사용자가 카카오 계정으로 로그인을 하면, 카카오 서버가 사용자에게  동의화면을 출력하여 인가를 위한 사용자 동의를 요청한다.
    - 여기서 동의 화면은 애플리케이션의 동의 항목 설정에 따라 구성된다.
- 사용자가 필수 동의 항목 및 선택 동의 항목을 체크한다.
- 카카오서버는 서버의 redirect uri로 인가코드를 전달한다.

### (2) 토큰 받기
- 서버가 redirect uri로 전달받은 인가코드로, 토큰 받기를 요청한다.
    - POST /oauth/token
    - ``` java
          POST /oauth/token HTTP/1.1
          Host: kauth.kakao.com
        ```
- 카카오 서버가 토큰을 발급해 전달해준다.

### (3) 사용자 로그인 처리
- 사용자 로그인 처리는 서비스 자체에서 해준다.
- 서버가 발급받은 엑세스 토큰으로 사용자 정보 가져오기를 요청하여, 사용자의 정보를 조회해 서비스 회원인지 확인해준다.
- 서비스에서 필요한 로그인 절차를 수행하고, 카카오 로그인한 사용자의 서비스 로그인 처리를 완료한다.

**Comment by daily1313** [comment]
## 카카오 소셜 로그인 흐름

![kakaologin_sequence](https://user-images.githubusercontent.com/88074556/211263092-8a5e44f8-cb68-46ec-ac9b-e8b6f2d25d2b.png)

### 인가 코드 받기
![kakaologin_code](https://user-images.githubusercontent.com/88074556/211264035-c9cb8dda-755d-477f-a39d-c575b4bda180.png)
- GET요청 주소  : /oauth/authorize?client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code 
- Host: kauth.kakao.com
- 클라이언트가 카카오 로그인 요청
- 서비스 서버에서 카카오 Auth 서버측으로 Get요청(URI : /oauth/authorize)을 보낸다.
- 카카오 Auth 서버에서 카카오 로그인 요청을 보내고 클라이언트가 로그인을 한다. 
- Clinet가 Auth 서버에게 동의 응답을 보내면 Auth 서버에서 Service 서버(302 Redirect URI)로 인가 코드 전달  

### 토큰 받기
- Post요청 주소 : POST /oauth/token 
- Host: kauth.kakao.com
Content-type: application/x-www-form-urlencoded;charset=utf-8
- 서비스 서버에서 카카오 Auth 서버로 Post요청(URI : /oauth/token)을 보낸다
- 카카오 Auth 서버에서 Service 서버로 토큰을 발급해준다.

### 사용자 로그인 처리
- OpenID Connect 사용시 (주의 사항 : scope 파라미터 값에 openid를 반드시 포함시켜줘야 한다.)
- ID 토큰 유효성 검증, 서비스 서버에서 발급받은 토큰으로 사용자 정보 조회 -> 로그인 완료
 
### 로그아웃 처리
- POST /v1/user/logout 
- Host: kapi.kakao.com
- Authorization: Bearer ${ACCESS_TOKEN}/KakaoAK ${APP_ADMIN_KEY}

< 카카오 소셜 로그인 로직 참고 자료 >
[https://antdev.tistory.com/37](https://antdev.tistory.com/37)

**Comment by weejinyoung** [comment]
![카카오OAuth2](https://user-images.githubusercontent.com/90890216/211268553-59ae4f43-d7ce-4617-82d2-98bad1ce909a.png)

Resource Server : 카카오

Authorization Server : 어쨌든 카카오

Resource Owner : 유저

Client : 심야식당

```
// 7번 과정
@GetMapping("/login/kakao")

public BaseResponse<LoginResponseDto> kakaoLogin(HttpServletRequest request) {

    String code = request.getParameter("code");
// 8번 과정
    String kakaoAccessToken = oauthService.getKakaoAccessToken(code).getAccessToken();
// 발급받은 엑세스 토큰
    return new BaseResponse<>(oauthService.kakaoLogin(kakaoAccessToken));
}
```

```
public KakaoTokenDto getKakaoAccessToken(String code) {

    RestTemplate rt = newRestTemplate();//통신용 템플릿 for HTTP통신 단순화 (스프링에서 지원하는 REST서비스 호출방식)
HttpHeaders headers = newHttpHeaders();
MultiValueMap<String, String> params =newLinkedMultiValueMap<>();

/* Kakao공식 문서에 따라 헤더,바디 값 구성 */
headers.add("Content-type", "application/x-www-form-urlencoded;charset=utf-8");

    params.add("grant_type", "authorization_code");
    params.add("client_id", KAKAO_CLIENT_ID);
    params.add("redirect_uri", KAKAO_REDIRECT_URI);
    params.add("code", code);//인가 코드 요청 시 받은 인가 코드 값 from프론트엔드

HttpEntity<MultiValueMap<String, String>> kakaoTokenRequest =newHttpEntity<>(params, headers);
log.info("KakaoTokenRequest: {}", kakaoTokenRequest);

// Kakao로부터 Access Token수신
// 8번과정 요청해서 9번과정 발급
ResponseEntity<String> accessTokenResponse = rt.exchange(
            "https://kauth.kakao.com/oauth/token",
            HttpMethod.POST,
            kakaoTokenRequest,
            String.class
);

// JSON Parsing (KakaoTokenDto)
ObjectMapper objectMapper =newObjectMapper();
    KakaoTokenDto kakaoTokenDto =null;
try{
        kakaoTokenDto = objectMapper.readValue(accessTokenResponse.getBody(), KakaoTokenDto.class);
    }catch(JsonProcessingException e) {
log.debug("Kakao Access Token(KakaoTokenDto) JSON Parsing 에 실패했습니다.");
    }

return kakaoTokenDto;
}
```
![카카오OAuth2](https://user-images.githubusercontent.com/90890216/211355832-9ca588ed-8898-41ce-b158-596f1f1e31e0.png)
```
// 8번과정 요청해서 9번과정 발급
ResponseEntity<String> accessTokenResponse = rt.exchange(
            "https://kauth.kakao.com/oauth/token",
            HttpMethod.POST,
            kakaoTokenRequest,
            String.class
);
```

**Comment by weejinyoung** [comment]
공부 끝
